package: nbpresent

platform:
  - linux-64
  - linux-32
  - osx-64
  - win-64
  # - win-32

engine:
  - python=2.7
  - python=3.4
  - python=3.5

script:
  - conda build conda.recipe -c javascript -c mutirri -c cpcloud -c anaconda-nb-extensions

build_targets: conda
