package: nbpresent

platform:
  - linux-64
  - linux-32
  - osx-64
  - win-64
  - win-32

engine:
  - python=3.5
  - python=3.4
  - python=2.7

script:
  - conda build conda.recipe -c javascript -c mutirri -c cpcloud -c anaconda-nb-extensions -c auto

build_targets: conda

---

platform: win-32
engine: python=2.7
exclude: true
