name: nbpresent
channels:
  - anaconda-nb-extensions
  - cpcloud
  - javascript
  - mutirri
  - auto
  - bokeh
dependencies:
  - anaconda-client
  - coverage
  - flake8
  - ipywidgets
  - mock
  - nb_config_manager
  - nodejs
  - nose
  - notebook
  - requests
