name: nbpresent
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - coverage
  - flake8= <3.7.8  # Latest breaks under py27
  - ipywidgets >=5.1.5
  - mock
  - nodejs
  - nose
  - notebook >=4.2.0
  - python
  - requests
