name: nbpresent
channels:
  - anaconda-nb-extensions
  - javascript
  - mutirri
  - cpcloud
dependencies:
  - anaconda-client
  - ipywidgets
  - nodejs
  - notebook
  - nb_config_manager
  - coverage
  - flake8
  - mock
  - requests
