package:
  name: nbpresent
  version: "3.0.2"

source:
  path: ../

build:
  number: 1

requirements:
  build:
    - nodejs
    - notebook >=4.2.0
    - python
    - setuptools

  run:
    - notebook >=4.2.0
    - python

test:
  requires:
    - coverage
    - flake8
    - ipywidgets <5
    - nodejs
    - nose
    - notebook >=4.2.0
    - python
    - requests
    - fontconfig  # [linux]
    - freetype  # [linux]
    - mock  # [py2k]

about:
  summary: Next generation slides for Jupyter Notebooks
  home: https://github.com/Anaconda-Platform/nbpresent
  license_file: LICENSE
  license: BSD License
