package:
  name: nbpresent
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}


requirements:
  build:
    - mistune !=0.7.2
    - nb_config_manager
    - nodejs
    - notebook <5
    - python
    - setuptools
    - funcsigs # [py2k]
    - npm # [win]
    - npm # [linux32]
  run:
    - mistune !=0.7.2
    - nb_config_manager
    - notebook <5
    - python
    - funcsigs # [py2k]

test:
  files:
    - package.json
  requires:
    - coverage
    - flake8
    - ipywidgets
    - nb_config_manager
    - nodejs
    - nose
    - notebook < 5
    - python
    - requests
    - fontconfig # [linux]
    - freetype # [linux]
    - mock # [py2k]
    - funcsigs # [py2k]
    - npm # [win]
    - npm # [linux32]


about:
  summary: Next generation slides for Jupyter Notebooks
  home: https://github.com/Anaconda-Server/nbpresent
  license_file: LICENSE
  license: BSD License
