package:
  name: nbpresent
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}


requirements:
  build:
    - nodejs
    - notebook >=4.2.0
    - python
    - setuptools
    - vs2008_runtime # [win-64]
    - vs2015_runtime # [win-64]

  run:
    - notebook >=4.2.0
    - python

test:
  files:
    - package.json
    - setup.cfg
  requires:
    - coverage
    - flake8
    - ipywidgets
    - nodejs
    - nose
    - notebook >=4.2.0
    - python
    - requests
    - fontconfig # [linux]
    - freetype # [linux]
    - mock # [py2k]
    - vs2008_runtime # [win-64]
    - vs2015_runtime # [win-64]

about:
  summary: Next generation slides for Jupyter Notebooks
  home: https://github.com/Anaconda-Platform/nbpresent
  license_file: LICENSE
  license: BSD License
